### ISSUE TITLE
Hello, are there any other modules that can be added to improve the effect?

### ISSUE THREAD

**Issue by 66cmw** [affctivai/coglier#1]
Hello, thank you for sharing. I would like to ask if you have made any improvements based on the original thesis project, or just modified some parameters. The results according to your code are beyond the results written in the paper.

**Comment by bhyungk** [comment]
> Hello, thank you for sharing. I would like to ask if you have made any improvements based on the original thesis project, or just modified some parameters. The results according to your code are beyond the results written in the paper.

Our methodology is applicable to any model. The paper is currently being reviewed, and code showing improved performance will also be released soon.
